events {
    worker_connections 1024;
}

http {
    include mime.types;
    server {
        listen 8080;

        location /geerule/ {
            # Forward all requests to the 'frontend' service container
            proxy_pass http://localhost:8000/geerule/; # backend app runs on port 8000
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/ {
            # Forward all requests to the 'frontend' service container
            proxy_pass http://localhost:8000/api/; # backend app runs on port 8000
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            try_files $uri $uri/ /index.html;
        }
    }
}
